### ISSUE TITLE
Authorize - Client is not associated with a SmartApp in location ...

### ISSUE THREAD

**Issue by Karman40** [alexking/StatusThing#12]
Authorize 6***9 to access your Works With SmartThings devices.

6***9 will be able to...

View and receive information and events from any of your connected Things.
Trigger any of your connected Things or Routines to take actions on your behalf. Voice control of Routines might be limited (e.g. Routines with unlocking and disarming may not run for security reasons).
From:

Client is not associated with a SmartApp in location ....

Any idea?

**Comment by alexking** [comment]
I haven't used the SmartThings platform for quite a few years now, and that message sounds different - it's quite possible the process for setting up the `app.groovy` code for your account has changed. I'd look for any documentation they might have on using oauth with custom apps.
