### ISSUE TITLE
Menu Bar Issues

### ISSUE THREAD

**Issue by dougc84** [alexking/StatusThing#8]
After downloading the app and fighting through Chrome vs. Safari, I found two bugs relating to the menu bar icon/text:

__1. StatusThing does not display in the menubar, because I have the dark theme enabled on OS X 10.11.__

The resolution would be to create a condition based on OS X's theme and use a different font color.

__2. StatusThing is incredibly narrow, because I have no thermostats.__

With no thermostat selected, the click area becomes a tiny, tiny sliver.  The current workaround I'm using was to add these lines on line 93, after the conditionals in `updateItemsAndTemperatures`, but before the return value:

```groovy
    temperatureItems << [
    	'id'	: '0',
        'name'	: 'NoTemperature',
        'value'	: 0,
        'unit'	: 'F'
    ]
```

However, this displays `0°` in the menu at all times.  An alternative display option when the `temperatureItems` array is empty would be optimal here.

---

I'd send a pull request for these things, but I'm well-versed in scripting and web development, not OS X development.  Thanks for the cool app though, thanks for building it!

**Comment by alexking** [comment]
1. Ah yes, I do have a bug setup for this (#4) but I haven't had time to figure out how it works with templates vs icons 
2. Hm, it should be doing this automatically, but as a temporary fix you can turn off "Show temperature in status bar" to show an icon instead. But it'd ought to do that as soon as it realizes you don't have any temperatures...

**Comment by dougc84** [comment]
Oh, you're right about point 2.  I may have missed that because the icon is hidden on the dark menu bar and enabled it by just clicking around.  So, scratch that.  However, that checkbox should probably be disabled if there aren't any temperature readouts, but that's pretty minor UI design and doesn't warrant an issue.

So, point 1 only.  And since you already have an issue open for point 1, I'll close this.  Thanks for the quick response!
